spring:
  application:
    name: jrebel-license-server
  freemarker:
    enabled: true
    prefix: /
    suffix: .ftl
    template-loader-path: classpath:/templates/
  mvc:
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: INFO
    com.imjcker.jrebel: DEBUG
  file:
    name: ${user.home}/logs/jrebel.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

server:
  port: 9090
